services:
  ## docker hub
  dockerhub:
    container_name: reg-docker-hub
    image: registry:latest
    restart: always
    environment:
      #- proxy=http://host:port
      #- http=$proxy
      #- https=$proxy
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry-hub.yml:/etc/docker/registry/config.yml
      #- ./htpasswd:/auth/htpasswd
    ports:
      - 51000:5000
    networks:
      - registry-net


  ## ghcr.io
  ghcr:
    container_name: reg-ghcr
    image: registry:latest
    restart: always
    environment:
      #- proxy=http://host:port
      #- http=$proxy
      #- https=$proxy
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry-ghcr.yml:/etc/docker/registry/config.yml
      #- ./htpasswd:/auth/htpasswd
    ports:
      - 52000:5000
    networks:
      - registry-net

  ## gcr.io
  gcr:
    container_name: reg-gcr
    image: registry:latest
    restart: always
    environment:
      #- proxy=http://host:port
      #- http=$proxy
      #- https=$proxy
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry-gcr.yml:/etc/docker/registry/config.yml
      #- ./htpasswd:/auth/htpasswd
    ports:
      - 53000:5000
    networks:
      - registry-net

  ## k8s.gcr.io
  k8sgcr:
    container_name: reg-k8s-gcr
    image: registry:latest
    restart: always
    environment:
      #- proxy=http://host:port
      #- http=$proxy
      #- https=$proxy
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry-k8sgcr.yml:/etc/docker/registry/config.yml
      #- ./htpasswd:/auth/htpasswd
    ports:
      - 54000:5000
    networks:
      - registry-net

 ## registry.k8s.io
  k8s:
    container_name: reg-k8s
    image: registry:latest
    restart: always
    environment:
      #- proxy=http://host:port
      #- http=$proxy
      #- https=$proxy
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry-k8s.yml:/etc/docker/registry/config.yml
      #- ./htpasswd:/auth/htpasswd
    ports:
      - 55000:5000
    networks:
      - registry-net
  
  ## quay.io
  quay:
    container_name: reg-quay
    image: registry:latest
    restart: always
    environment:
      #- proxy=http://host:port
      #- http=$proxy
      #- https=$proxy
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry-quay.yml:/etc/docker/registry/config.yml
      #- ./htpasswd:/auth/htpasswd
    ports:
      - 56000:5000
    networks:
      - registry-net


  ## UI
  registry-ui:
    container_name: registry-ui
    image: dqzboy/docker-registry-ui:latest
    environment:
      - DOCKER_REGISTRY_URL=http://reg-docker-hub:5000
      # [必须]使用 openssl rand -hex 16 生成唯一值
      - SECRET_KEY_BASE=9f18244a1e1179fa5aa4a06a335d01b2
      # 启用Image TAG 的删除按钮
      - ENABLE_DELETE_IMAGES=true
      - NO_SSL_VERIFICATION=true
    restart: always
    ports:
      - 50000:8080
    networks:
      - registry-net

networks:
  registry-net:
